Repository cojar/jigumiyak, pull requests merged in 2023-08, with the labels that each got.

#8 자유게시판 RQ-0094 외 여러 건
  src/main/java/com/ll/jigumiyak/board/Board.java
  src/main/java/com/ll/jigumiyak/board/BoardController.java
  src/main/java/com/ll/jigumiyak/board/BoardForm.java
  src/main/java/com/ll/jigumiyak/board/BoardRepository.java
  src/main/java/com/ll/jigumiyak/board/BoardService.java
  src/main/java/com/ll/jigumiyak/board_comment/BoardComment.java
  src/main/java/com/ll/jigumiyak/board_comment/BoardCommentController.java
  src/main/java/com/ll/jigumiyak/board_comment/BoardCommentForm.java
  src/main/java/com/ll/jigumiyak/board_comment/BoardCommentService.java
  src/main/java/com/ll/jigumiyak/board_recomment/BoardRecomment.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/resources/static/navbar.css
  src/main/resources/static/test.css
  src/main/resources/templates/board_detail.html
  src/main/resources/templates/board_form.html
  src/main/resources/templates/board_list.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/form_errors.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/navbar.html
  src/test/java/com/ll/jigumiyak/JigumiyakApplicationTests.java
Labels: enhancement

#10 로그인, 회원가입 - RQ-0024 외
  src/main/java/com/ll/jigumiyak/security/DefaultFailureHandler.java
  src/main/java/com/ll/jigumiyak/security/DefaultSuccessHandler.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/java/com/ll/jigumiyak/user/UserSecurityService.java
  src/main/resources/static/login.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement

#11 공통 - RQ-0001, 0002
  src/main/resources/static/common.js
  src/main/resources/static/login.js
  src/main/resources/static/signup.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/signup.html
Labels: enhancement

#13 자유게시판 댓글 버그 수정
  src/main/java/com/ll/jigumiyak/board_comment/BoardCommentController.java
Labels: bug fix

#14 보안 - RQ-0000
  .gitignore
  src/main/resources/application-dev.properties
Labels: enhancement

#15 빌드 - RQ-0000
  Dockerfile
Labels: bug fix

#16 게시판 글 상세/ 마이페이지 프론트
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/templates/board_detail.html
  src/main/resources/templates/board_form.html
  src/main/resources/templates/board_list.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/navbar.html
Labels: enhancement

#19 공지사항
  src/main/java/com/ll/jigumiyak/notice/NoticeController.java
  src/main/java/com/ll/jigumiyak/notice/NoticeService.java
  src/main/java/com/ll/jigumiyak/notice_comment/NoticeCommentController.java
  src/main/resources/templates/notice_detail.html
  src/main/resources/templates/notice_form.html
Labels: bug fix

#20 게시판목록 rq-0098
  .gitignore
  src/main/java/com/ll/jigumiyak/board/BoardController.java
  src/main/java/com/ll/jigumiyak/board/BoardRepository.java
  src/main/java/com/ll/jigumiyak/board/BoardService.java
  src/main/resources/templates/board_list.html
Labels: enhancement

#21 공통 - RQ-0001, 0002
  src/main/java/com/ll/jigumiyak/security/DefaultSuccessHandler.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/static/signup.js
  src/main/resources/templates/navbar.html
Labels: bug fix

#22 CL-12
  src/main/java/com/ll/jigumiyak/notice/Notice.java
  src/main/java/com/ll/jigumiyak/notice/NoticeController.java
  src/main/java/com/ll/jigumiyak/notice/NoticeRepository.java
  src/main/java/com/ll/jigumiyak/notice/NoticeService.java
  src/main/resources/static/common.js
  src/main/resources/templates/notice_detail.html
  src/main/resources/templates/notice_list.html
Labels: enhancement, bug fix

#24 Feature fr
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/templates/findIDandPW.html
  src/main/resources/templates/inquiry_list.html
  src/main/resources/templates/inquiry_main.html
  src/main/resources/templates/navbar.html
Labels: enhancement

#25 게시판 목록 RQ-0095 외
  src/main/java/com/ll/jigumiyak/board/Board.java
  src/main/java/com/ll/jigumiyak/board/BoardController.java
  src/main/java/com/ll/jigumiyak/board/BoardService.java
  src/main/resources/templates/board_list.html
Labels: enhancement

#26 회원가입 - RQ-0044, 0046, 0047, 0048, 0049, 0052
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/java/com/ll/jigumiyak/user/UserSignupForm.java
  src/main/java/com/ll/jigumiyak/util/RsData.java
  src/main/resources/static/login.js
  src/main/resources/static/signup.css
  src/main/resources/static/signup.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement, bug fix

#27 로그인 - RQ-0036, 0037
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/templates/find_user.html
  src/main/resources/templates/login.html
Labels: enhancement

#28 로그인 - RQ-0028, 0029, 0030, 0032
  build.gradle
  src/main/java/com/ll/jigumiyak/security/CustomDetails.java
  src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
  src/main/java/com/ll/jigumiyak/security/FailureHandler.java
  src/main/java/com/ll/jigumiyak/security/SecurityConfig.java
  src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccount.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccountRepository.java
  src/main/java/com/ll/jigumiyak/social_account/SocialInfo.java
  src/main/java/com/ll/jigumiyak/user/UserSecurityService.java
  src/main/resources/static/image/login_google.png
  src/main/resources/static/image/login_kakao.png
  src/main/resources/templates/login.html
Labels: enhancement

#29 product list front
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/resources/templates/inquiry_list.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/product_list.html
  src/test/java/com/ll/jigumiyak/JigumiyakApplicationTests.java
Labels: enhancement

#31 로그인 - RQ-0219, 0220, 0221, 0222, 0223
  src/main/java/com/ll/jigumiyak/security/CustomDetails.java
  src/main/java/com/ll/jigumiyak/security/CustomRole.java
  src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
  src/main/java/com/ll/jigumiyak/user/SiteUser.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/java/com/ll/jigumiyak/user/UserRepository.java
  src/main/java/com/ll/jigumiyak/user/UserRole.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/find_user.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/find_user.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/signup.html
Labels: enhancement

#32 보안 - RQ-0000
  .gitignore
  src/main/resources/application-prod.properties
  src/main/resources/application-prod.properties.default
  src/main/resources/application.properties
Labels: enhancement

#33 Feature cl 03
  src/main/resources/static/test.css
  src/main/resources/templates/layout.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/sidebar.html
Labels: enhancement

#34 공지사항
  src/main/java/com/ll/jigumiyak/notice/NoticeController.java
  src/main/java/com/ll/jigumiyak/notice/NoticeRepository.java
  src/main/java/com/ll/jigumiyak/notice/NoticeService.java
  src/main/resources/templates/notice_detail.html
  src/main/resources/templates/notice_list.html
Labels: bug fix

#36 상품(파일)
  src/main/java/com/ll/jigumiyak/api_and_data_load/ApiCaller.java
  src/main/java/com/ll/jigumiyak/api_and_data_load/ApiService.java
  src/main/java/com/ll/jigumiyak/file/FileRepository.java
  src/main/java/com/ll/jigumiyak/file/FileService.java
  src/main/java/com/ll/jigumiyak/file/GenFile.java
  src/main/java/com/ll/jigumiyak/nutrient/Nutrient.java
  src/main/java/com/ll/jigumiyak/nutrient/NutrientRepository.java
  src/main/java/com/ll/jigumiyak/nutrient/NutrientService.java
  src/main/java/com/ll/jigumiyak/nutrient_category/NutrientCategoryService.java
  src/main/java/com/ll/jigumiyak/product/Product.java
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/java/com/ll/jigumiyak/product/ProductForm.java
  src/main/java/com/ll/jigumiyak/product/ProductRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/resources/templates/product_form.html
  src/main/resources/templates/product_list.html
Labels: enhancement

#38 상품목록
  src/main/java/com/ll/jigumiyak/api_and_data_load/ApiCaller.java
  src/main/java/com/ll/jigumiyak/api_and_data_load/ApiService.java
  src/main/java/com/ll/jigumiyak/nutrient/NutrientRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/java/com/ll/jigumiyak/product/ProductRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/resources/templates/notice_list.html
  src/main/resources/templates/product_list.html
Labels: enhancement

#39 로그인 - RQ-0031
  src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
  src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
Labels: enhancement

#40 로그인 - RQ-0223
  src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
  src/main/java/com/ll/jigumiyak/user/SiteUser.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
Labels: enhancement

#41 게시글 관리 Feature cl 27
  .gitignore
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/board/BoardController.java
  src/main/java/com/ll/jigumiyak/board/BoardRepository.java
  src/main/java/com/ll/jigumiyak/board/BoardService.java
  src/main/java/com/ll/jigumiyak/board_comment/BoardCommentService.java
  src/main/java/com/ll/jigumiyak/board_recomment/BoardRecommentRepository.java
  src/main/java/com/ll/jigumiyak/board_recomment/BoardRecommentService.java
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/admin_board.html
  src/main/resources/templates/admin/admin_board_comment.html
  src/main/resources/templates/admin/admin_board_recomment.html
  src/main/resources/templates/admin/administration.html
  src/main/resources/templates/board_detail.html
Labels: enhancement

#42 버그 수정 Feature cl 27
  src/main/resources/templates/admin/admin_board.html
  src/main/resources/templates/admin/admin_board_comment.html
  src/main/resources/templates/admin/admin_board_recomment.html
Labels: bug fix

#43 Feature cl 18
  src/main/java/com/ll/jigumiyak/api_and_data_load/ApiCaller.java
  src/main/java/com/ll/jigumiyak/file/FileService.java
  src/main/java/com/ll/jigumiyak/nutrient/NutrientRepository.java
  src/main/java/com/ll/jigumiyak/nutrient/NutrientService.java
  src/main/java/com/ll/jigumiyak/product/Product.java
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/java/com/ll/jigumiyak/product/ProductForm.java
  src/main/java/com/ll/jigumiyak/product/ProductRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/resources/templates/product_detail.html
  src/main/resources/templates/product_form.html
  src/main/resources/templates/product_list.html
Labels: enhancement

#44 마이페이지 - RQ-0166, 0167, 0168, 0169, 0170, 0171
  src/main/java/com/ll/jigumiyak/address/AddressService.java
  src/main/java/com/ll/jigumiyak/security/CustomRole.java
  src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
  src/main/java/com/ll/jigumiyak/social_account/GoogleOauth2.java
  src/main/java/com/ll/jigumiyak/social_account/KakaoOauth2.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccount.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccountController.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccountRepository.java
  src/main/java/com/ll/jigumiyak/social_account/SocialAccountService.java
  src/main/java/com/ll/jigumiyak/social_account/SocialInfo.java
  src/main/java/com/ll/jigumiyak/social_account/SocialOauth2.java
  src/main/java/com/ll/jigumiyak/user/SiteUser.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/java/com/ll/jigumiyak/user/UserModifyPasswordForm.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/java/com/ll/jigumiyak/util/CommonUtil.java
  src/main/resources/static/css/user_modify.css
  src/main/resources/static/js/user_find.js
  src/main/resources/static/js/user_modify.js
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/user_find.html
  src/main/resources/templates/user_modify.html
Labels: enhancement

#45 상품 상세 Feature fr
  src/main/resources/static/test.css
  src/main/resources/templates/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/product_detail.html
  src/main/resources/templates/product_list.html
Labels: enhancement

#48 cart bug fix
  src/main/java/com/ll/jigumiyak/cart/CartController.java
  src/main/resources/static/js/product.js
  src/main/resources/templates/product_detail.html
Labels: bug fix

#50 문의내역 Feature cl 15
  src/main/java/com/ll/jigumiyak/inquiry/Inquiry.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryForm.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryRepository.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
  src/main/resources/templates/board_detail.html
  src/main/resources/templates/faq/faq.html
  src/main/resources/templates/inquiry/inquiry_detail.html
  src/main/resources/templates/inquiry/inquiry_success.html
  src/main/resources/templates/inquiry/list.html
Labels: enhancement

#51 결제 - RQ-0154, 0155, 0156, 0157, 0158, 0159, 0160, 0161 및 상품 상세, 장바구니 hotfix
  build.gradle
  src/main/java/com/ll/jigumiyak/cart/Cart.java
  src/main/java/com/ll/jigumiyak/cart/CartController.java
  src/main/java/com/ll/jigumiyak/cart/CartRepository.java
  src/main/java/com/ll/jigumiyak/cart/CartService.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItem.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemForm.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/java/com/ll/jigumiyak/purchase/Purchase.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseForm.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseRepository.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseState.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/application-prod.properties.default
  src/main/resources/static/css/purchase.css
  src/main/resources/static/js/product.js
  src/main/resources/static/js/product_detail.js
  src/main/resources/static/js/purchase.js
  src/main/resources/templates/cart.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/product_detail.html
  src/main/resources/templates/purchase/fail.html
  src/main/resources/templates/purchase/purchase.html
  src/main/resources/templates/purchase/success.html
Labels: enhancement, bug fix

#53 장바구니 - RQ-0133, 0134, 0144, 0145, 0146, 0147, 0148, 0149, 0151, 0152
  src/main/java/com/ll/jigumiyak/cart/CartController.java
  src/main/java/com/ll/jigumiyak/cart/CartService.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItem.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemController.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemRepository.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/resources/application-prod.properties.default
  src/main/resources/static/css/cart.css
  src/main/resources/static/js/cart.js
  src/main/resources/templates/cart.html
  src/main/resources/templates/purchase/purchase.html
Labels: enhancement

#54 상품 상세
  src/main/java/com/ll/jigumiyak/nutrient_category/NutrientCategory.java
  src/main/java/com/ll/jigumiyak/product/Product.java
  src/main/java/com/ll/jigumiyak/product/ProductController.java
  src/main/java/com/ll/jigumiyak/product/ProductDetailForm.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/java/com/ll/jigumiyak/product_review/ProductReview.java
  src/main/java/com/ll/jigumiyak/product_review/ProductReviewController.java
  src/main/java/com/ll/jigumiyak/product_review/ProductReviewForm.java
  src/main/java/com/ll/jigumiyak/product_review/ProductReviewRepository.java
  src/main/java/com/ll/jigumiyak/product_review/ProductReviewService.java
  src/main/resources/templates/product_detail.html
  src/main/resources/templates/product_detail_form.html
  src/main/resources/templates/product_form.html
  src/main/resources/templates/product_review_form.html
Labels: duplicate, enhancement

#55 장바구니 - RQ-0151 fix
  src/main/resources/static/js/cart.js
  src/main/resources/templates/cart.html
Labels: bug fix

#56 문의하기 관리 Feature cl 34
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/user/UserRepository.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/java/com/ll/jigumiyak/util/CommonUtil.java
  src/main/resources/templates/admin/inquiry_detail.html
  src/main/resources/templates/board_detail.html
  src/main/resources/templates/footer.html
  src/main/resources/templates/navbar.html
Labels: enhancement

#58 메인페이지 Feature fr
  src/main/java/com/ll/jigumiyak/MainController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/navbar.html
Labels: enhancement

#59 장바구니 - RQ-0142, 0143, 0150
  src/main/java/com/ll/jigumiyak/cart/CartController.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemController.java
  src/main/resources/static/js/cart.js
  src/main/resources/templates/cart.html
Labels: enhancement

#60 문의하기 Feature cl 14
  src/main/java/com/ll/jigumiyak/inquiry/Inquiry.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryForm.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
  src/main/resources/templates/admin/inquiry_detail.html
  src/main/resources/templates/inquiry/inquiry_detail.html
  src/main/resources/templates/inquiry/inquiry_form.html
Labels: enhancement

#61 결제 - RQ-0162, 0164
  src/main/java/com/ll/jigumiyak/address/AddressService.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemController.java
  src/main/java/com/ll/jigumiyak/cart_item/CartItemService.java
  src/main/java/com/ll/jigumiyak/purchase/Purchase.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseRepository.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
  src/main/java/com/ll/jigumiyak/purchase_detail/PurchaseDetailRepository.java
  src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItem.java
  src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItemRepository.java
  src/main/java/com/ll/jigumiyak/purchase_item/PurchaseItemService.java
  src/main/java/com/ll/jigumiyak/security/SuccessHandler.java
  src/main/resources/static/js/purchase.js
  src/main/resources/templates/cart.html
  src/main/resources/templates/purchase/fail.html
  src/main/resources/templates/purchase/purchase.html
  src/main/resources/templates/purchase/success.html
Labels: enhancement

#62 회원관리 - RQ-0194
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/security/CustomRole.java
  src/main/java/com/ll/jigumiyak/security/CustomSecurityService.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/admin_user.html
Labels: enhancement

#63 채팅 Feature chat
  build.gradle
  src/main/java/com/ll/jigumiyak/chat/ChatController.java
  src/main/java/com/ll/jigumiyak/chat/ChatHandler.java
  src/main/java/com/ll/jigumiyak/chat/Contact.java
  src/main/java/com/ll/jigumiyak/chat/ContactController.java
  src/main/java/com/ll/jigumiyak/chat/ContactRepository.java
  src/main/java/com/ll/jigumiyak/chat/ContactService.java
  src/main/java/com/ll/jigumiyak/chat/WebSocketConfig.java
  src/main/resources/static/starboot/assets/favicon.ico
  src/main/resources/static/starboot/css/chatStyle.css
  src/main/resources/static/starboot/css/styles.css
  src/main/resources/static/test.css
  src/main/resources/templates/chat.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/navbar.html
  src/main/resources/templates/product_list.html
  src/main/resources/templates/sidebar.html
Labels: enhancement

#64 회원관리 - RQ-0195, 0196
  src/main/java/com/ll/jigumiyak/security/CustomRole.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/java/com/ll/jigumiyak/user/UserService.java
  src/main/resources/static/css/admin_user.css
  src/main/resources/static/js/admin_user.js
  src/main/resources/templates/admin/admin_user.html
Labels: enhancement

#65 마크다운 Feature markdown
  build.gradle
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/inquiry/InquiryService.java
  src/main/java/com/ll/jigumiyak/util/CommonUtil.java
  src/main/resources/templates/admin/inquiry_detail.html
  src/main/resources/templates/board_detail.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/faq/faq.html
  src/main/resources/templates/inquiry/inquiry_detail.html
  src/main/resources/templates/inquiry/list.html
  src/main/resources/templates/notice_detail.html
Labels: enhancement, bug fix

#66 마이페이지 Feature cl 36
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/templates/mypage.html
Labels: enhancement

#67 공지사항 관리 Feature cl 33
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/notice/NoticeRepository.java
  src/main/java/com/ll/jigumiyak/notice/NoticeService.java
  src/main/java/com/ll/jigumiyak/notice_comment/NoticeCommentRepository.java
  src/main/java/com/ll/jigumiyak/notice_comment/NoticeCommentService.java
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/notice.html
  src/main/resources/templates/admin/notice_comment.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/notice_list.html
  src/main/resources/templates/sidebar.html
Labels: enhancement

#69 결제 및 배송 - RQ-0209, 0210, 0212
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/static/js/admin_purchase.js
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/admin_purchase.html
Labels: enhancement

#70 장바구니 - RQ-0149 fix
  src/main/resources/static/js/cart.js
  src/main/resources/templates/cart.html
Labels: bug fix

#72 Feature chat
  src/main/java/com/ll/jigumiyak/chat/Contact.java
  src/main/java/com/ll/jigumiyak/chat/ContactController.java
  src/main/java/com/ll/jigumiyak/chat/ContactRepository.java
  src/main/java/com/ll/jigumiyak/chat/ContactService.java
  src/main/resources/static/test.css
  src/main/resources/templates/board_list.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/index.html
  src/main/resources/templates/notice_list.html
Labels: enhancement, bug fix

#73 마이페이지, 결제, 정산 등 - RQ-0176, 0178, 0179
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/cash_log/CashLog.java
  src/main/java/com/ll/jigumiyak/cash_log/CashLogRepository.java
  src/main/java/com/ll/jigumiyak/cash_log/CashLogService.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseRepository.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseService.java
  src/main/java/com/ll/jigumiyak/receipt/Receipt.java
  src/main/java/com/ll/jigumiyak/user/UserController.java
  src/main/resources/static/js/purchase_detail.js
  src/main/resources/templates/admin/admin_purchase.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/purchase/detail.html
Labels: enhancement

#76 잔여 작업
  build.gradle
  src/main/java/com/ll/jigumiyak/cart/CartController.java
  src/main/java/com/ll/jigumiyak/purchase/PurchaseController.java
  src/main/resources/static/js/product_detail.js
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/product_detail.html
Labels: enhancement, bug fix

#77 rq-207
  src/main/java/com/ll/jigumiyak/admin/AdminController.java
  src/main/java/com/ll/jigumiyak/product/Product.java
  src/main/java/com/ll/jigumiyak/product/ProductRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/product.html
  src/main/resources/templates/survey_result.html
Labels: enhancement

#78 hot-fix
  src/main/java/com/ll/jigumiyak/inquiry/InquiryController.java
  src/main/java/com/ll/jigumiyak/product/ProductRepository.java
  src/main/java/com/ll/jigumiyak/product/ProductService.java
  src/main/java/com/ll/jigumiyak/user/UserRepository.java
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage.html
Labels: bug fix

#79 Hot-Fix
  src/main/resources/templates/admin/ad_navbar.html
  src/main/resources/templates/admin/administration.html
  src/main/resources/templates/product_detail.html
Labels: bug fix
